### ISSUE TITLE
status code is smallest than minimum value: 100

### ISSUE THREAD

**Issue by deimjons** [Medzoner/traefik-plugin-cors-preflight#8]
I tried to use this plugin but received: "status code is smallest than minimum value: 100". It is no matter what value I will insert. 

<img width="249" alt="image" src="https://github.com/Medzoner/traefik-plugin-cors-preflight/assets/10740038/265d7373-0c65-436b-9654-24f95daf7b19">

<img width="1638" alt="image" src="https://github.com/Medzoner/traefik-plugin-cors-preflight/assets/10740038/c90d2d65-c88f-4b3e-b98a-484a485c23c9">

**Comment by Medzoner** [comment]
Hi @deimjons , I didn't see your problem. I'm sorry. Documentation was been updated, thanks @sturman :

**Comment by sturman** [comment]
> corspreflight: code: 200 method: OPTIONS

```yaml
corspreflight: 
  code: 200 
  method: OPTIONS
```
